# fly.toml app configuration file generated for fly-pr-preview-apps-test on 2024-03-27T14:10:20-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-pr-preview-apps-test'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
